//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;

    public class InterviewSchedule
    {
        public int InterviewScheduleId { get; set; } // Identity column (auto-generated)
        public int StudentId { get; set; } // Foreign key
        public DateTime ScheduleDate { get; set; }
        public bool IsAppeared { get; set; } = false; // Default value
        public bool IsSelected { get; set; } = false; // Default value
        public decimal? Package { get; set; } = null; // Nullable
        public DateTime? JoiningDate { get; set; } = null; // Nullable
    }

}
