//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacementDetail
    {
        public int PlacementId { get; set; }
        public string AcademicYear { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime RegistrationStart { get; set; }
        public System.DateTime RegistrationEnd { get; set; }
        public string Criteria { get; set; }
    }
}
