//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;

    public class StudentRegistration
    {
        public int StudentId { get; set; }
        public int PlacementId { get; set; }
        public DateTime RegisteredOn { get; set; }
        public int Status { get; set; }

        // Navigation properties
        public virtual PlacementDetail PlacementDetail { get; set; }
    }

}
